// File type: Vercel Serverless Function (Node.js API route)
// Path: /api/pets.js

import { createClient } from "@supabase/supabase-js";

const THIRTY_MINUTES_SECONDS = 30 * 60;

// Debug warning: Supabase client for database operations
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
);

// Admin client with service role key (bypasses RLS)
const supabaseAdmin = process.env.SUPABASE_SERVICE_ROLE_KEY 
  ? createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY)
  : null;

// Verify admin credentials against database
async function verifyAdmin(username, password) {
  if (!username || !password) return false;

  try {
    const { data: admin, error } = await supabase
      .from("admin_users")
      .select("id, username, is_active")
      .eq("username", username)
      .eq("password", password)
      .eq("is_active", true)
      .single();

    return !error && admin;
  } catch (err) {
    console.error("[Auth Error]:", err);
    return false;
  }
}

// Log action to audit_log table
async function logAudit(username, actionType, petId, petName, changes) {
  if (!supabaseAdmin) {
    console.warn("[Audit Warning] Service role key not configured, skipping audit log");
    return;
  }
  
  try {
    await supabaseAdmin
      .from("audit_log")
      .insert([
        {
          username,
          action_type: actionType,
          pet_id: petId,
          pet_name: petName,
          changes: changes || {}
        }
      ]);
  } catch (err) {
    console.error("[Audit Log Error]:", err);
  }
}

// Set CORS headers for cross-origin requests
function setCorsHeaders(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, X-Admin-Username, X-Admin-Password");
  res.setHeader("Access-Control-Max-Age", "86400"); // Cache preflight for 24 hours
}

export default async function handler(req, res) {
  // Set CORS headers for ALL requests
  setCorsHeaders(res);

  // Handle preflight OPTIONS request
  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  // Route to appropriate handler
  switch (req.method) {
    case "GET":
      return handleGet(req, res);
    case "POST":
      return handlePost(req, res);
    case "PUT":
      return handlePut(req, res);
    case "DELETE":
      return handleDelete(req, res);
    default:
      res.setHeader("Allow", "GET, POST, PUT, DELETE, OPTIONS");
      return res.status(405).json({ error: "Method not allowed" });
  }
}

// GET: Fetch all pets from database
async function handleGet(req, res) {
  // Set CDN caching headers
  res.setHeader(
    "Cache-Control",
    "public, max-age=0, s-maxage=1800, stale-while-revalidate=1800"
  );

  try {
    // Debug warning: Now includes stats_type field for percentage/value display
    const { data: pets, error } = await supabase
      .from("pets")
      .select("id, name, rarity, stats, stats_type, value_normal, value_golden, value_rainbow, image_url, updated_at")
      .order("id", { ascending: false }); // Sort by ID descending (newest first)

    if (error) {
      console.error("[Supabase Error]:", error);
      return res.status(500).json({ error: "Failed to fetch pets" });
    }

    return res.status(200).json(pets || []);
  } catch (err) {
    console.error("[API Error]:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
}

// POST: Create new pet
async function handlePost(req, res) {
  const username = req.headers['x-admin-username'];
  const password = req.headers['x-admin-password'];

  console.log('[Backend] POST request - Username:', username);

  // Check if admin client is configured
  if (!supabaseAdmin) {
    console.error('[Backend] Service role key not configured');
    return res.status(500).json({ error: "Server configuration error" });
  }

  // Verify admin credentials
  const isValid = await verifyAdmin(username, password);
  if (!isValid) {
    console.log('[Backend] Authentication failed');
    return res.status(401).json({ error: "Unauthorized" });
  }

  try {
    // Debug warning: Now accepts text values for stats and value fields, plus stats_type
    const { name, rarity, stats, stats_type, value_normal, value_golden, value_rainbow, image_url } = req.body;

    // Validate required fields
    if (!name || !rarity) {
      return res.status(400).json({ error: "Name and rarity are required" });
    }

    // Insert into database using admin client (ID auto-generated by database)
    const { data: newPet, error } = await supabaseAdmin
      .from("pets")
      .insert([
        {
          name,
          rarity,
          stats: stats || '0',
          stats_type: stats_type || 'value',
          value_normal: value_normal || '0',
          value_golden: value_golden || '0',
          value_rainbow: value_rainbow || '0',
          image_url: image_url || null,
          updated_at: new Date().toISOString()
        }
      ])
      .select()
      .single();

    if (error) {
      console.error("[Supabase Error]:", error);
      return res.status(500).json({ error: "Failed to create pet" });
    }

    // Log to audit_log
    await logAudit(username, 'ADD', newPet.id, newPet.name, {
      name,
      rarity,
      stats: stats || '0',
      stats_type: stats_type || 'value',
      value_normal: value_normal || '0',
      value_golden: value_golden || '0',
      value_rainbow: value_rainbow || '0'
    });

    console.log('[Backend] Pet created successfully:', newPet.id);
    return res.status(201).json(newPet);
  } catch (err) {
    console.error("[API Error]:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
}

// PUT: Update existing pet
async function handlePut(req, res) {
  const username = req.headers['x-admin-username'];
  const password = req.headers['x-admin-password'];

  console.log('[Backend] PUT request - Username:', username);

  // Check if admin client is configured
  if (!supabaseAdmin) {
    console.error('[Backend] Service role key not configured');
    return res.status(500).json({ error: "Server configuration error" });
  }

  // Verify admin credentials
  const isValid = await verifyAdmin(username, password);
  if (!isValid) {
    console.log('[Backend] Authentication failed');
    return res.status(401).json({ error: "Unauthorized" });
  }

  try {
    // Extract pet ID from URL (e.g., /api/pets/123)
    const urlParts = req.url.split('/');
    const petId = urlParts[urlParts.length - 1];

    console.log('[Backend] Updating pet ID:', petId);

    if (!petId || petId === 'pets' || isNaN(petId)) {
      return res.status(400).json({ error: "Pet ID is required" });
    }

    // Get current pet data for comparison using admin client
    const { data: oldPet } = await supabaseAdmin
      .from("pets")
      .select("*")
      .eq("id", petId)
      .single();

    // Debug warning: Extract all fields including new stats_type
    const { name, rarity, stats, stats_type, value_normal, value_golden, value_rainbow, image_url } = req.body;

    // Validate required fields
    if (!name || !rarity) {
      return res.status(400).json({ error: "Name and rarity are required" });
    }

    // Update in database using admin client
    const { data: updatedPet, error } = await supabaseAdmin
      .from("pets")
      .update({
        name,
        rarity,
        stats: stats || '0',
        stats_type: stats_type || 'value',
        value_normal: value_normal || '0',
        value_golden: value_golden || '0',
        value_rainbow: value_rainbow || '0',
        image_url: image_url || null,
        updated_at: new Date().toISOString()
      })
      .eq("id", petId)
      .select()
      .single();

    if (error) {
      console.error("[Supabase Error]:", error);
      return res.status(500).json({ error: "Failed to update pet" });
    }

    if (!updatedPet) {
      return res.status(404).json({ error: "Pet not found" });
    }

    // Calculate what changed for audit log
    const changes = {};
    if (oldPet) {
      if (oldPet.name !== name) changes.name = { from: oldPet.name, to: name };
      if (oldPet.rarity !== rarity) changes.rarity = { from: oldPet.rarity, to: rarity };
      if (oldPet.stats !== stats) changes.stats = { from: oldPet.stats, to: stats };
      if (oldPet.stats_type !== stats_type) changes.stats_type = { from: oldPet.stats_type, to: stats_type };
      if (oldPet.value_normal !== value_normal) changes.value_normal = { from: oldPet.value_normal, to: value_normal };
      if (oldPet.value_golden !== value_golden) changes.value_golden = { from: oldPet.value_golden, to: value_golden };
      if (oldPet.value_rainbow !== value_rainbow) changes.value_rainbow = { from: oldPet.value_rainbow, to: value_rainbow };
      if (oldPet.image_url !== image_url) changes.image_url = { from: oldPet.image_url ? 'changed' : 'none', to: image_url ? 'changed' : 'none' };
    }

    // Log to audit_log
    await logAudit(username, 'EDIT', updatedPet.id, updatedPet.name, changes);

    console.log('[Backend] Pet updated successfully:', updatedPet.id);
    return res.status(200).json(updatedPet);
  } catch (err) {
    console.error("[API Error]:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
}

// DELETE: Remove pet from database
async function handleDelete(req, res) {
  const username = req.headers['x-admin-username'];
  const password = req.headers['x-admin-password'];

  console.log('[Backend] DELETE request - Username:', username);

  // Check if admin client is configured
  if (!supabaseAdmin) {
    console.error('[Backend] Service role key not configured');
    return res.status(500).json({ error: "Server configuration error" });
  }

  // Verify admin credentials
  const isValid = await verifyAdmin(username, password);
  if (!isValid) {
    console.log('[Backend] Authentication failed');
    return res.status(401).json({ error: "Unauthorized" });
  }

  try {
    // Extract pet ID from URL
    const urlParts = req.url.split('/');
    const petId = urlParts[urlParts.length - 1];

    console.log('[Backend] Deleting pet ID:', petId);

    if (!petId || petId === 'pets' || isNaN(petId)) {
      return res.status(400).json({ error: "Pet ID is required" });
    }

    // Get pet data before deletion for audit log using admin client
    const { data: pet } = await supabaseAdmin
      .from("pets")
      .select("*")
      .eq("id", petId)
      .single();

    // Delete from database using admin client
    const { error } = await supabaseAdmin
      .from("pets")
      .delete()
      .eq("id", petId);

    if (error) {
      console.error("[Supabase Error]:", error);
      return res.status(500).json({ error: "Failed to delete pet" });
    }

    // Log to audit_log
    if (pet) {
      await logAudit(username, 'DELETE', pet.id, pet.name, {
        deleted_pet: {
          name: pet.name,
          rarity: pet.rarity,
          stats: pet.stats,
          stats_type: pet.stats_type,
          value_normal: pet.value_normal,
          value_golden: pet.value_golden,
          value_rainbow: pet.value_rainbow
        }
      });
    }

    console.log('[Backend] Pet deleted successfully:', petId);
    return res.status(200).json({ success: true, message: "Pet deleted" });
  } catch (err) {
    console.error("[API Error]:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
}

// File type: Vercel Serverless Function (Node.js API route)
// Path: /api/pets.js
